$accent = rgb(cbcb76)
$accentAlpha = rgba(203, 203, 118, 0.8)
$text = rgb(e6e3d5)
$background = rgb(14140c)
$font = JetBrainsMono Nerd Font

# GENERAL
general {
    disable_loading_bar = true
    hide_cursor = true
}

# BACKGROUND
background {
    monitor =
    path = ~/.config/hypr/Wallpapers/pain.jpg
    blur_passes = 2
}

# TIME
label {
    monitor =
    text = $TIME12
    color = $accent
    font_size = 52
    font_family = $font
    position = -27, 0
    halign = right
    valign = top
}

# DATE
label {
    monitor =
    text = cmd[update:43200000] date +"%A, %d %B %Y"
    color = $text
    font_size = 20
    font_family = $font
    position = -30, -90
    halign = right
    valign = top
}

# USER AVATAR

image {
    monitor =
    path = ~/.face
    size = 100
    border_color = $accent

    position = 0, 75
    halign = center
    valign = center
}

# INPUT FIELD
input-field {
    monitor =
    size = 235, 50
    outline_thickness = 2
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true
    outer_color = rgb(202018)
    inner_color = rgb(14140c)
    font_color = rgb(e6e3d5)
    fade_on_empty = false
    placeholder_text = Logged in as $USER
    hide_input = false
    check_color = $accent
    fail_color = rgb(ffb4ab)
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
    font_family = monospace
    capslock_color = rgb(a4d0bd)
    position = 0, -35
    halign = center
    valign = center
}
